# Generated by Django 4.2.3 on 2026-07-08 19:04

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_comment='Email de connexion', max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('role', models.CharField(choices=[('student', 'طالب'), ('teacher', 'معلم'), ('regional_admin', 'مدير جهوي'), ('admin', 'مدير النظام')], db_comment='student/teacher/regional_admin/admin', default='student', max_length=20, verbose_name='الدور')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='صورة الملف الشخصي')),
                ('school', models.CharField(blank=True, db_comment='École de rattachement', max_length=200, verbose_name='المدرسة')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمين',
                'db_table_comment': 'Compte utilisateur central - toutes les identités',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(db_comment='Code wilaya officiel', unique=True, verbose_name='code')),
                ('name', models.CharField(db_comment='Nom de la wilaya', max_length=100, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'ولاية',
                'verbose_name_plural': 'الولايات',
                'db_table_comment': 'Régions administratives de Mauritanie',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(blank=True, max_length=200, verbose_name='المؤهل العلمي')),
                ('subjects', models.CharField(blank=True, max_length=500, verbose_name='المواد الدراسية')),
                ('years_of_experience', models.IntegerField(default=0, verbose_name='سنوات الخبرة')),
                ('user', models.OneToOneField(db_comment='FK UNIQUE vers User', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف المعلم',
                'verbose_name_plural': 'ملفات المعلمين',
                'db_table_comment': 'Profil étendu des enseignants',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('parent_name', models.CharField(blank=True, max_length=200, verbose_name='اسم ولي الأمر')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف ولي الأمر')),
                ('level', models.ForeignKey(blank=True, db_comment="Niveau scolaire actuel de l'étudiant", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='curriculum.level', verbose_name='الصف الدراسي الحالي')),
                ('user', models.OneToOneField(db_comment='FK UNIQUE vers User', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف الطالب',
                'verbose_name_plural': 'ملفات الطلاب',
                'db_table_comment': 'Profil étendu des étudiants',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='wilaya',
            field=models.ForeignKey(blank=True, db_comment="FK vers Wilaya - Wilaya de l'utilisateur", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.wilaya', verbose_name='الولاية'),
        ),
    ]
