# Generated by Django 4.2.27 on 2026-08-13 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='الرمز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('is_used', models.BooleanField(default=False, verbose_name='مستخدم')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='عدد المحاولات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_codes', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رمز إعادة تعيين كلمة المرور',
                'verbose_name_plural': 'رموز إعادة تعيين كلمة المرور',
                'ordering': ['-created_at'],
            },
        ),
    ]
