# Generated by Django 4.2.3 on 2026-01-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
