version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Montage en direct pour le développement
      - sqlite_data:/app  # Pour persister la base SQLite
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=project.settings

volumes:
  sqlite_data: