# Generated by Django 4.2.3 on 2026-07-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_comment="Ex: 'ERR-U01-L01-001'", max_length=30, unique=True, verbose_name='رمز الخطأ')),
                ('category', models.CharField(choices=[('concept', 'خطأ مفاهيمي'), ('procedure', 'خطأ إجرائي'), ('careless', 'خطأ إهمالي')], max_length=20, verbose_name='فئة الخطأ')),
                ('error_type', models.CharField(max_length=500, verbose_name='وصف الخطأ المختصر')),
                ('root_cause', models.TextField(verbose_name='السبب الجذري')),
                ('severity_level', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية')], max_length=20, verbose_name='مستوى الخطورة')),
                ('feedback_message', models.TextField(blank=True, null=True, verbose_name='رسالة المساعدة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'نوع الخطأ',
                'verbose_name_plural': 'أنواع الأخطاء',
                'db_table_comment': "Catalogue d'erreurs - toujours liée à une Skill",
            },
        ),
        migrations.CreateModel(
            name='LogAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='إجابة الطالب')),
                ('is_correct', models.BooleanField(verbose_name='إجابة صحيحة')),
                ('error_type', models.CharField(blank=True, choices=[('concept', 'خطأ مفاهيمي'), ('procedure', 'خطأ إجرائي'), ('careless', 'خطأ إهمالي')], max_length=20, null=True, verbose_name='فئة الخطأ')),
                ('time_taken', models.IntegerField(blank=True, null=True, verbose_name='الوقت المستغرق بالثواني')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ والوقت')),
            ],
            options={
                'verbose_name': 'سجل إجابة',
                'verbose_name_plural': 'سجلات الإجابات',
                'db_table_comment': 'Historique append-only des réponses des étudiants',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=0, verbose_name='عدد المحاولات')),
                ('correct_count', models.IntegerField(default=0, verbose_name='عدد الإجابات الصحيحة')),
                ('mastery', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='نسبة الإتقان')),
                ('consecutive_correct', models.IntegerField(default=0, verbose_name='الإجابات الصحيحة المتتالية')),
                ('last_error_type', models.CharField(blank=True, choices=[('concept', 'خطأ مفاهيمي'), ('procedure', 'خطأ إجرائي'), ('careless', 'خطأ إهمالي')], max_length=20, null=True, verbose_name='نوع آخر خطأ')),
                ('status', models.CharField(choices=[('not_started', 'لم يبدأ'), ('in_progress', 'قيد التقدم'), ('mastered', 'أتقن')], default='not_started', max_length=20, verbose_name='الحالة')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('mastered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإتقان')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='آخر نشاط')),
            ],
            options={
                'verbose_name': 'تقدم الطالب',
                'verbose_name_plural': 'تقدم الطلاب',
                'db_table_comment': 'Progression courante - PK composite (student_id, skill_id)',
            },
        ),
    ]
