# Generated by Django 4.2.3 on 2026-01-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان النشاط')),
                ('activity_type', models.CharField(choices=[('multiple_choice', 'اختيار من متعدد'), ('true_false', 'صح أو خطأ'), ('matching', 'توصيل'), ('drag_drop', 'سحب وإفلات'), ('fill_blank', 'ملء الفراغات'), ('short_answer', 'إجابة قصيرة')], max_length=50, verbose_name='نوع النشاط')),
                ('question', models.TextField(verbose_name='السؤال')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='الخيارات')),
                ('correct_answer', models.JSONField(verbose_name='الإجابة الصحيحة')),
                ('points', models.IntegerField(default=10, verbose_name='النقاط')),
                ('explanation', models.TextField(blank=True, verbose_name='التفسير')),
                ('time_limit', models.IntegerField(blank=True, null=True, verbose_name='الحد الزمني بالثواني')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'نشاط',
                'verbose_name_plural': 'الأنشطة',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(verbose_name='إجابة الطالب')),
                ('is_correct', models.BooleanField(default=False, verbose_name='إجابة صحيحة')),
                ('score', models.IntegerField(default=0, verbose_name='الدرجة')),
                ('time_taken', models.IntegerField(verbose_name='الوقت المستغرق بالثواني')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المحاولة')),
            ],
            options={
                'verbose_name': 'محاولة الطالب',
                'verbose_name_plural': 'محاولات الطلاب',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0, verbose_name='إجمالي النقاط')),
                ('mastery_level', models.CharField(choices=[('not_started', 'لم يبدأ'), ('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم'), ('mastered', 'أتقن')], default='not_started', max_length=20, verbose_name='مستوى الإتقان')),
                ('completion_percentage', models.FloatField(default=0.0, verbose_name='نسبة الإنجاز')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='آخر وصول')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('completed_activities', models.ManyToManyField(blank=True, related_name='completed_by', to='assessment.activity')),
            ],
            options={
                'verbose_name': 'تقدم الطالب',
                'verbose_name_plural': 'تقدم الطلاب',
            },
        ),
    ]
