# Generated by Django 4.2.3 on 2026-07-08 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='skill',
            field=models.ForeignKey(db_comment='La skill suivie', on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='skills.skill', verbose_name='المهارة'),
        ),
    ]
