# Generated by Django 4.2.3 on 2026-07-08 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0002_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='student',
            field=models.ForeignKey(db_comment="L'étudiant", on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
        migrations.AddField(
            model_name='loganswer',
            name='chunk',
            field=models.ForeignKey(db_comment='Le chunk pratiqué', on_delete=django.db.models.deletion.CASCADE, related_name='answer_logs', to='skills.chunk', verbose_name='القطعة'),
        ),
        migrations.AddField(
            model_name='loganswer',
            name='error_detail',
            field=models.ForeignKey(blank=True, db_comment="Détail de l'erreur", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='assessment.error', verbose_name='تفاصيل الخطأ'),
        ),
        migrations.AddField(
            model_name='loganswer',
            name='skill',
            field=models.ForeignKey(db_comment='La skill', on_delete=django.db.models.deletion.CASCADE, related_name='answer_logs', to='skills.skill', verbose_name='المهارة'),
        ),
        migrations.AddField(
            model_name='loganswer',
            name='student',
            field=models.ForeignKey(db_comment="L'étudiant", on_delete=django.db.models.deletion.CASCADE, related_name='answer_logs', to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
        migrations.AddField(
            model_name='error',
            name='skill',
            field=models.ForeignKey(db_comment='Skill associée (obligatoire)', on_delete=django.db.models.deletion.CASCADE, related_name='error_catalog', to='skills.skill', verbose_name='المهارة'),
        ),
        migrations.AddConstraint(
            model_name='studentprogress',
            constraint=models.UniqueConstraint(fields=('student', 'skill'), name='unique_student_skill_progress'),
        ),
    ]
