# Generated by Django 4.2.3 on 2026-01-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('total_time_spent', models.IntegerField(default=0, verbose_name='إجمالي الوقت بالدقائق')),
                ('completed_units', models.IntegerField(default=0, verbose_name='الوحدات المكتملة')),
                ('total_score', models.IntegerField(default=0, verbose_name='إجمالي النقاط')),
                ('avg_mastery_level', models.FloatField(default=0.0, verbose_name='متوسط مستوى الإتقان')),
            ],
            options={
                'verbose_name': 'تحليل التعلم',
                'verbose_name_plural': 'تحليلات التعلم',
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'معلومات'), ('warning', 'تحذير'), ('error', 'خطأ'), ('security', 'أمن')], max_length=20, verbose_name='مستوى السجل')),
                ('category', models.CharField(choices=[('user', 'مستخدم'), ('content', 'محتوى'), ('assessment', 'تقييم'), ('system', 'نظام')], max_length=20, verbose_name='الفئة')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='وكيل المستخدم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'سجل النظام',
                'verbose_name_plural': 'سجلات النظام',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=0, verbose_name='إجمالي الطلاب')),
                ('active_students', models.IntegerField(default=0, verbose_name='الطلاب النشطين')),
                ('total_units_created', models.IntegerField(default=0, verbose_name='إجمالي الوحدات المنشأة')),
                ('student_engagement_rate', models.FloatField(default=0.0, verbose_name='معدل تفاعل الطلاب')),
                ('avg_student_progress', models.FloatField(default=0.0, verbose_name='متوسط تقدم الطلاب')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'لوحة تحكم المعلم',
                'verbose_name_plural': 'لوحات تحكم المعلمين',
            },
        ),
    ]
