"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from datetime import timedelta
from datetime import timedelta
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-174)sxx419n2spv8vsvav#j%7cv_!#9h(w%x2=pmc#wc35erpb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',  
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
    'django_extensions',
    
    # Local apps
    'users',
    'core',
    'curriculum',
    'assessment',
    'analytics',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # ← AJOUTEZ-CE CI
    'django.middleware.locale.LocaleMiddleware',  # ← TRÈS IMPORTANT pour la langue
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'ar'  # ou 'ar-sa', 'ar-ma', etc.


TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CORS
# CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='http://localhost:3000').split(',')
CORS_ALLOW_CREDENTIALS = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}
# Custom User Model
AUTH_USER_MODEL = 'users.User'
# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}


"""
إضافة إلى settings.py
"""

# إعدادات Admin
# ADMIN_SITE_HEADER = 'منصة Ed-Tech التعليمية'
# ADMIN_SITE_TITLE = 'لوحة تحكم المنصة'
# ADMIN_INDEX_TITLE = 'مرحباً بك في نظام إدارة المنصة التعليمية'
# ADMIN_SITE_BRAND = "نظام إدارة المنصة التعليمية",
# settings.py
# settings.py

JAZZMIN_SETTINGS = {
    # Titres
    "site_title": "لوحة تحكم المنصة",
    "site_header": "منصة Ed-Tech التعليمية",
    "site_brand": "نظام إدارة المنصة التعليمية",
    "site_logo": None,
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    
    # Message de bienvenue
    "welcome_sign": "مرحباً بك في نظام إدارة المنصة التعليمية",
    "copyright": "منصة Ed-Tech © 2024",
    "search_model": ["auth.User", "users.User"],
    
    # Interface utilisateur
    "show_ui_builder": True,  # Activez pour personnaliser visuellement
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    
    # Thème LIGHT au lieu de dark
    "theme": "cosmo",  # ← Thème clair (cosmo, flatly, litera, lumen, minty, pulse, sandstone, simplex, sketchy, spacelab, united, yeti)
    "dark_mode_theme": "darkly",  # Pour le mode sombre optionnel
    
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    
    # Support RTL
    "rtl_support": True,
    "language_chooser": False,
    
    # Menu sidebar
    "show_sidebar": True,
    "user_avatar": None,
    "related_modal_active": False,
    
    # CSS personnalisé pour RTL et responsive
    "custom_css": "css/admin_custom.css",  # ← Nous créerons ce fichier
    
    "custom_js": None,
    
    # Barre de navigation
    "navbar_fixed": True,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "actions_sticky_top": True,
    
    # Responsive settings
    "responsive": True,  # ← Activer le responsive
    "sidebar_collapsible": True,  # ← Menu repliable sur mobile
    
    # Icônes des applications
    "icons": {
        # Applications principales
        "auth": "fas fa-users-cog",  # Authentification
        "auth.user": "fas fa-user",  # Utilisateurs
        "auth.Group": "fas fa-users",  # Groupes
        
        # Votre application "users"
        "users": "fas fa-user-graduate",  # Application users
        "users.user": "fas fa-user-circle",  # Modèle User
        
        # Votre application "analytics"
        "analytics": "fas fa-chart-network",  # Application analytics
        "analytics.learninganalytics": "fas fa-chart-line",  # Modèle LearningAnalytics
        "analytics.teacherdashboard": "fas fa-chalkboard-teacher",  # Modèle TeacherDashboard
        "analytics.systemlog": "fas fa-clipboard-list",  # Modèle SystemLog
        
        # Votre application "curriculum"
        "curriculum": "fas fa-book-open",  # Application curriculum
        "curriculum.subject": "fas fa-book",  # Modèle Subject
        "curriculum.unit": "fas fa-file-alt",  # Modèle Unit
        "curriculum.lesson": "fas fa-chalkboard",  # Modèle Lesson
        
        # Votre application "assessment"
        "assessment": "fas fa-clipboard-check",  # Application assessment
        "assessment.quiz": "fas fa-question-circle",  # Modèle Quiz
        "assessment.question": "fas fa-question",  # Modèle Question
        "assessment.answer": "fas fa-check-circle",  # Modèle Answer
        
        # Votre application "core"
        "core": "fas fa-cogs",  # Application core
    },
    
    # Icônes par défaut (si modèle non spécifié)
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-file",
}

# Configuration UI pour thème clair
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    
    # Thème clair
    "brand_colour": "navbar-white",
    "accent": "accent-primary",
    
    # Navbar en blanc
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": True,
    "navbar_fixed": True,
    
    # Layout
    "layout_boxed": False,
    "footer_fixed": False,
    
    # Sidebar en clair
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-primary",  # ← Light au lieu de dark
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    
    # Thème
    "theme": "cosmo",  # Même thème clair
    "dark_mode_theme": "darkly",
    
    # Boutons
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    
    "actions_sticky_top": True,
}
# إعدادات الترجمة
LANGUAGE_CODE = 'ar'
TIME_ZONE = 'Asia/Riyadh'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# إعدادات التنسيق للأرقام العربية
DECIMAL_SEPARATOR = ','
THOUSAND_SEPARATOR = '.'
USE_THOUSAND_SEPARATOR = True

# إعدادات التاريخ والوقت العربية
DATE_FORMAT = 'Y-m-d'
DATETIME_FORMAT = 'Y-m-d H:i:s'
TIME_FORMAT = 'H:i:s'

# اللغات المدعومة
LANGUAGES = [
    ('ar', 'العربية'),
    ('en', 'English'),
]

# مجلدات الترجمة
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]