# Generated by Django 4.2.3 on 2026-07-08 19:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_comment="Ex: 'SK-U01-L01-C01'", max_length=30, unique=True, verbose_name='رمز المهارة')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المهارة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المهارة')),
                ('skill_type', models.CharField(choices=[('conceptual', 'مفاهيمي'), ('operational', 'عملياتي')], db_comment='Conceptual OU Operational - DOIT correspondre au goal_type parent', max_length=20, verbose_name='نوع المهارة')),
                ('difficulty', models.IntegerField(db_comment='CHECK (1-5)', default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='مستوى الصعوبة')),
                ('mastery_threshold', models.FloatField(default=0.8, verbose_name='عتبة الإتقان')),
                ('required_consecutive_correct', models.IntegerField(default=3, verbose_name='عدد المحاولات الصحيحة المتتالية المطلوبة')),
                ('order_index', models.IntegerField(default=0, verbose_name='الترتيب داخل الهدف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('goal', models.ForeignKey(db_comment='Goal parent', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='curriculum.goal', verbose_name='الهدف')),
            ],
            options={
                'verbose_name': 'مهارة',
                'verbose_name_plural': 'المهارات',
                'db_table_comment': 'Compétence précise - hérite du type de son Goal parent',
                'ordering': ['goal', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_comment="Ex: 'CH-U01-L01-C01'", max_length=30, unique=True, verbose_name='رمز القطعة')),
                ('chunk_type', models.CharField(choices=[('rule', 'قاعدة'), ('example', 'مثال'), ('practice', 'تمرين'), ('error', 'خطأ'), ('hint', 'تلميح'), ('real_life', 'تطبيق')], db_comment='rule/example/practice/error/hint/real_life', max_length=20, verbose_name='نوع القطعة')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان')),
                ('content', models.TextField(help_text='Contenu textuel (HTML autorisé)', verbose_name='المحتوى')),
                ('correct_answer', models.TextField(blank=True, help_text='Requis si practice', null=True, verbose_name='الإجابة الصحيحة')),
                ('options', models.JSONField(blank=True, default=list, null=True, verbose_name='خيارات الإجابة (QCM)')),
                ('difficulty', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='الصعوبة')),
                ('order_index', models.IntegerField(default=0, verbose_name='ترتيب العرض المقترح')),
                ('points', models.IntegerField(default=1, verbose_name='النقاط')),
                ('time_limit', models.IntegerField(blank=True, null=True, verbose_name='الحد الزمني بالثواني')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('skill', models.ForeignKey(db_comment='Skill parente', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='skills.skill', verbose_name='المهارة')),
            ],
            options={
                'verbose_name': 'قطعة محتوى',
                'verbose_name_plural': 'قطع المحتوى',
                'db_table_comment': 'Plus petite unité de contenu (rule/example/practice/error/hint/real_life)',
                'ordering': ['skill', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite', models.ForeignKey(db_comment='Skill prérequise', on_delete=django.db.models.deletion.CASCADE, related_name='required_for_skills', to='skills.skill', verbose_name='المهارة المطلوبة')),
                ('skill', models.ForeignKey(db_comment='Skill ayant des prérequis', on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites_required', to='skills.skill', verbose_name='المهارة')),
            ],
            options={
                'verbose_name': 'متطلب سابق',
                'verbose_name_plural': 'المتطلبات السابقة',
                'db_table_comment': 'Dépendances entre compétences (PK composite skill_id, prerequisite_id)',
                'ordering': ['skill', 'prerequisite'],
                'indexes': [models.Index(fields=['skill'], name='skills_prer_skill_i_f95d52_idx'), models.Index(fields=['prerequisite'], name='skills_prer_prerequ_c1b58b_idx')],
                'unique_together': {('skill', 'prerequisite')},
            },
        ),
    ]
