# Generated by Django 4.2.3 on 2026-07-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('conceptual', 'مفاهيمي'), ('operational', 'عملياتي')], db_comment='Conceptual OU Operational', max_length=20, verbose_name='نوع الهدف')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان الهدف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الهدف')),
                ('order_index', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'هدف تعليمي',
                'verbose_name_plural': 'الأهداف التعليمية',
                'db_table_comment': 'Objectif pédagogique Conceptual/Operational',
                'ordering': ['lesson', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_comment="Ex: 'U01-L01'", max_length=30, unique=True, verbose_name='رمز الدرس')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الدرس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('order_index', models.IntegerField(default=0, verbose_name='الترتيب داخل الوحدة')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'الدروس',
                'db_table_comment': "Leçon au sein d'une unité",
                'ordering': ['unit', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment="Ex: 'السنة الأولى ابتدائية'", max_length=100, verbose_name='اسم السنة')),
                ('code', models.CharField(db_comment="Code court (ex: 'PRIM-1')", max_length=20, unique=True, verbose_name='الرمز')),
                ('order_index', models.IntegerField(verbose_name='الترتيب داخل المرحلة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'سنة دراسية',
                'verbose_name_plural': 'السنوات الدراسية',
                'db_table_comment': "Année scolaire au sein d'une étape",
                'ordering': ['stage__order_index', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment="Ex: 'المرحلة الابتدائية'", max_length=100, verbose_name='اسم المرحلة')),
                ('code', models.CharField(db_comment="Code court (ex: 'PRIM')", max_length=20, unique=True, verbose_name='الرمز')),
                ('order_index', models.IntegerField(db_comment='Ordre des étapes', verbose_name='ترتيب المراحل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'مرحلة',
                'verbose_name_plural': 'المراحل',
                'db_table_comment': 'Étape scolaire globale (Primaire, Secondaire, Lycée)',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المادة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('color', models.CharField(blank=True, help_text='Code couleur hexadécimal, ex: #3498db', max_length=7, verbose_name='اللون')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='الأيقونة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مادة',
                'verbose_name_plural': 'المواد',
                'db_table_comment': "Matière scolaire au sein d'une année",
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_comment="Ex: 'U01'", max_length=20, unique=True, verbose_name='رمز الوحدة')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الوحدة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('main_goal_description', models.TextField(blank=True, db_comment='Objectif global (texte descriptif)', null=True, verbose_name='الهدف الرئيسي')),
                ('central_question', models.TextField(blank=True, db_comment="Question centrale qui guide l'apprentissage", null=True, verbose_name='السؤال المركزي')),
                ('main_skill_domain', models.CharField(blank=True, max_length=200, verbose_name='مجال الكفاءة الرئيسي')),
                ('order_index', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشورة')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='units/', verbose_name='الصورة المصغرة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'وحدة تعليمية',
                'verbose_name_plural': 'الوحدات التعليمية',
                'db_table_comment': "Unité d'apprentissage - contient objectif et question centrale",
                'ordering': ['subject', 'order_index'],
            },
        ),
    ]
