# Generated by Django 4.2.3 on 2026-01-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان القسم')),
                ('content_type', models.CharField(choices=[('text', 'نص'), ('image', 'صورة'), ('video', 'فيديو'), ('audio', 'صوت'), ('interactive', 'تفاعلي')], max_length=20, verbose_name='نوع المحتوى')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='البيانات الوصفية')),
            ],
            options={
                'verbose_name': 'قسم المحتوى',
                'verbose_name_plural': 'أقسام المحتوى',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المادة')),
                ('grade', models.IntegerField(verbose_name='الصف الدراسي')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='الأيقونة')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='اللون')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مادة',
                'verbose_name_plural': 'المواد',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('learning_objective', models.TextField(verbose_name='الهدف التعليمي')),
                ('duration_minutes', models.IntegerField(default=15, verbose_name='المدة بالدقائق')),
                ('difficulty', models.CharField(choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب')], default='medium', max_length=20, verbose_name='مستوى الصعوبة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='units/', verbose_name='الصورة المصغرة')),
                ('video_url', models.URLField(blank=True, verbose_name='رابط الفيديو')),
                ('audio_url', models.URLField(blank=True, verbose_name='رابط الصوت')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'وحدة تعليمية',
                'verbose_name_plural': 'الوحدات التعليمية',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
