# Generated by Django 4.2.3 on 2026-07-08 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='created_by',
            field=models.ForeignKey(blank=True, db_comment='Créateur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_units', to=settings.AUTH_USER_MODEL, verbose_name='أنشئت بواسطة'),
        ),
        migrations.AddField(
            model_name='unit',
            name='subject',
            field=models.ForeignKey(db_comment='Matière parente', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='curriculum.subject', verbose_name='المادة'),
        ),
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.ForeignKey(db_comment='Année scolaire', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='curriculum.level', verbose_name='السنة الدراسية'),
        ),
        migrations.AddField(
            model_name='level',
            name='stage',
            field=models.ForeignKey(db_comment='Étape parente', on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='curriculum.stage', verbose_name='المرحلة'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(db_comment='Unité parente', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.unit', verbose_name='الوحدة'),
        ),
        migrations.AddField(
            model_name='goal',
            name='lesson',
            field=models.ForeignKey(db_comment='Leçon parente', on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='curriculum.lesson', verbose_name='الدرس'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'level')},
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.UniqueConstraint(fields=('lesson', 'goal_type'), name='unique_goal_type_per_lesson'),
        ),
    ]
